import type { Metadata } from "next";
import "./globals.css";
import { Fira_Sans } from '@next/font/google';
import Header from "./components/Header";

// Load FiraGo font with specific weights and styles
const firaGo = Fira_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Add desired font weights
  style: ['normal', 'italic'], // Add specific styles
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={firaGo.className}
      >
        <Header />

        {children}
      </body>
    </html>
  );
}
