import type { Metadata } from "next";
import "./globals.css";
import localfont from '@next/font/local';
import Header from "./components/Header";
import { GlobalContextProvider } from "./context/globalContext";
import AddAgent from "./components/addAgent/AddAgent";

const firaGo = localfont({
  src: [
    {
      path: './fonts/FiraGo-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: "--font-fira-go",
});

const helveticaNeue = localfont({
  src: [
    {
      path: './fonts/HelveticaNeueBlack.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: "--font-helveticaNeue",
});

export const metadata: Metadata = {
  title: "Redberry Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GlobalContextProvider >

        <body
          className={firaGo.variable + " " + helveticaNeue.variable}
        >
          <AddAgent />
          <Header />

          {children}
        </body>
      </GlobalContextProvider>
    </html>
  );
}
